import os


DISCORD_LOGIN_TOKEN = os.environ.get('ACCUWEATHER_DISCORDBOT_DISCORD_TOKEN')
ACCUWEATHER_API_KEY = os.environ.get('ACCUWEATHER_API_KEY')
LANGUAGE = os.environ.get('ACCUWEATHER_DISCORDBOT_LANGUAGE', None)
